env:
  browser: true
  es2021: true

extends:
  - airbnb
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module

plugins:
  - react
  - functional
  - '@typescript-eslint'

parser: '@typescript-eslint/parser'

rules:
  import/extensions: 0
  import/no-unresolved: 0
  no-console: 0
  functional/no-conditional-statements: 0
  functional/no-expression-statements: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statement: 0
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  react/function-component-definition: [2, { 'namedComponents': 'arrow-function' }]
  testing-library/no-debug: 0
  react/jsx-filename-extension: [1, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }]
